In [2]:
#10
from math import radians as mradians
from numpy import radians as nradians

print('math              numpy             Equals?')
for degree in [75, 180, 90]:
    print(round(mradians(degree), 15), round(nradians(degree), 15), mradians(degree) == nradians(degree))

math              numpy             Equals?
1.308996938995747 1.308996938995747 True
3.141592653589793 3.141592653589793 True
1.570796326794897 1.570796326794896 True


In [3]:
#11
import numpy as np
print([num*(num + 1) for num in np.arange(2, 22, 2)])

[6, 20, 42, 72, 110, 156, 210, 272, 342, 420]


In [4]:
#12
matrix = np.matrix([[i*10+j+1 for j in range(7)] for i in range(11)])
print(matrix)

[[  1   2   3   4   5   6   7]
 [ 11  12  13  14  15  16  17]
 [ 21  22  23  24  25  26  27]
 [ 31  32  33  34  35  36  37]
 [ 41  42  43  44  45  46  47]
 [ 51  52  53  54  55  56  57]
 [ 61  62  63  64  65  66  67]
 [ 71  72  73  74  75  76  77]
 [ 81  82  83  84  85  86  87]
 [ 91  92  93  94  95  96  97]
 [101 102 103 104 105 106 107]]


In [25]:
#13
from sympy import *
import random

arr = [[random.randint(0, 20) for j in range(7)] for i in range(4)]
maxn, minn = np.max(arr), np.min(arr)
a, b = symbols('a b')
a, b = solve([a*maxn+b*a*maxn+b-1, a*minn+b*a*minn+b], (a, b))[0]

for i in range(len(arr)):
    for j in range(len(arr[0])):
        x = arr[i][j]
        arr[i][j] = a*x+b*a*x+b

print(arr)

[[7/9, 11/18, 5/6, 5/18, 1/2, 1/18, 0], [7/18, 11/18, 1/9, 7/18, 1/6, 1/2, 1/6], [1/18, 4/9, 5/18, 5/9, 13/18, 8/9, 11/18], [1/6, 5/9, 1/3, 2/9, 13/18, 1, 1/9]]


In [32]:
#14

arr = [[np.random.randint(0, 11) for j in range(10)] for i in range(8)]
minsum = 10000
for line in arr:
    if np.sum(line) < minsum:
        minsum = np.sum(line)
        minline = line

print(arr.index(minline), minline)

4 [8, 1, 2, 3, 2, 5, 1, 8, 5, 7]


In [33]:
#15

arr = [np.random.randint(101) for i in range(20)]
newarr = [30 if num < 30 else 70 if num > 70 else num for num in arr]
print(newarr)

[70, 50, 59, 70, 30, 64, 30, 70, 70, 69, 70, 30, 70, 30, 70, 53, 57, 61, 36, 48]


4